### ISSUE TITLE
kde plasma integration not working

### ISSUE THREAD

**Issue by tazihad** [flathub/io.github.martchus.syncthingtray#4]
kde plasma dolphin integration not working with flatpak version.

**Comment by Martchus** [comment]
It is not supported by the Flatpak because it is not possible to support it for technical reasons. I have already asked KDE developers about it. This limitation is already stated on https://martchus.github.io/syncthingtray/#downloads-section.

Of course if you know something that we don't feel free to provide a PR yourself. In the meantime I suppose we can close this issue.

**Comment by Martchus** [comment]
Maybe this limitation should be made more clear on the Flatpak description, though.
